require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'Guardfile'
    - 'db/migrate/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
